[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "3HShZpiDZyeraqGZc2gGNWqTP4fY7adee2srxd9FfY2Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
