[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "5CYtVSiW8aqygrMrw34mmXSdcA7Rt86V1MKGpVGSTjs9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
